name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_scm_client_id: ${{ secrets.SCM_CLIENT_ID }}
      TF_VAR_scm_client_secret: ${{ secrets.SCM_CLIENT_SECRET }}
      TF_VAR_scm_tsg_id: ${{ secrets.SCM_TSG_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
